# Generated by Django 5.1 on 2024-08-29 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database_models', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='_card_uid',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='_card_number',
            field=models.CharField(max_length=16, unique=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='_cvv',
            field=models.CharField(max_length=3, unique=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='_company_token',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
