# Generated by Django 5.1 on 2024-09-11 21:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('database_models', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('_company_token', models.CharField(blank=True, max_length=15, null=True, unique=True)),
                ('_balance', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(blank=True, null=True, upload_to='uploads/%Y/%m/%d/')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_card_number', models.CharField(blank=True, max_length=16, null=True, unique=True)),
                ('_cvv', models.CharField(blank=True, max_length=3, null=True)),
                ('_balance', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('_card_uid', models.CharField(blank=True, max_length=6, null=True, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database_models.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_balance_before', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('card_balance_after', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('company_balance_before', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('company_balance_after', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='database_models.card')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='database_models.company')),
                ('receipt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database_models.receipt')),
            ],
        ),
    ]
