# Generated by Django 5.1 on 2024-09-05 16:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database_models', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='receipt',
            old_name='receipt_img',
            new_name='img',
        ),
        migrations.RemoveField(
            model_name='company',
            name='balance',
        ),
        migrations.RemoveField(
            model_name='receipt',
            name='card',
        ),
        migrations.RemoveField(
            model_name='receipt',
            name='company',
        ),
        migrations.RemoveField(
            model_name='receipt',
            name='created',
        ),
        migrations.AddField(
            model_name='card',
            name='_card_uid',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='company',
            name='_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='card',
            name='_card_number',
            field=models.CharField(max_length=16, unique=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='_cvv',
            field=models.CharField(max_length=3, unique=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='_company_token',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True),
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_balance_before', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('card_balance_after', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('company_balance_before', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('company_balance_after', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='database_models.card')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='database_models.company')),
                ('receipt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database_models.receipt')),
            ],
        ),
    ]
