# Generated by Django 5.1 on 2024-09-09 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database_models', '0002_rename_receipt_img_receipt_img_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='_card_number',
            field=models.CharField(blank=True, max_length=16, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='_cvv',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
    ]
