# Generated by Django 5.1 on 2024-09-09 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database_models', '0004_alter_profile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='_card_uid',
            field=models.CharField(blank=True, max_length=6, null=True, unique=True),
        ),
    ]
