# Generated by Django 5.1 on 2024-09-16 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database_models', '0007_alter_company_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='building',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='city',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='country',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='street',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
