# Generated by Django 5.1 on 2024-09-23 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database_models', '0009_profile_telegram_chat_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='telegram_chat_id',
            field=models.CharField(blank=True, default='', max_length=20, null=True),
        ),
    ]
