# Generated by Django 5.1 on 2024-09-27 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database_models', '0010_alter_profile_telegram_chat_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('value_type', models.CharField(choices=[('INT', 0), ('TEXT', []), ('BOOL', False)], default=str, max_length=100)),
                ('value', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
