# Generated by Django 5.1 on 2024-09-27 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database_models', '0011_servicesetting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicesetting',
            name='value_type',
            field=models.CharField(choices=[('int', 'INT'), ('str', 'TEXT'), ('bool', 'BOOL')], default='str', max_length=100),
        ),
    ]
