# Generated by Django 5.1 on 2024-10-18 12:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database_models', '0012_alter_servicesetting_value_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='_pin_code',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='transactions', to='database_models.card'),
        ),
    ]
