# Generated by Django 5.1 on 2024-11-13 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database_models', '0014_alter_card_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('admin', 'admin'), ('user', 'user')], default='user'),
        ),
    ]
