# Generated by Django 5.1 on 2024-11-13 21:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database_models', '0015_profile_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='IncreaseBalanceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_money', models.CharField(max_length=10)),
                ('attached_message', models.TextField()),
                ('request_status', models.CharField(choices=[('waiting', 'waiting'), ('accepted', 'accepted'), ('considered', 'considered'), ('denied', 'denied')], default='waiting')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database_models.card')),
            ],
        ),
    ]
