# Generated by Django 5.1 on 2024-11-13 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database_models', '0016_increasebalancerequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='increasebalancerequest',
            name='attached_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='increasebalancerequest',
            name='requested_money',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
