# Generated by Django 5.1 on 2025-01-02 13:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database_models', '0017_alter_increasebalancerequest_attached_message_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='companies', to='database_models.profile'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='card',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cards', to='database_models.profile'),
        ),
        migrations.AlterField(
            model_name='increasebalancerequest',
            name='card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='database_models.card'),
        ),
        migrations.AlterField(
            model_name='product',
            name='company_owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='database_models.company'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='database_models.card'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='database_models.company'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='receipt',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='transaction', to='database_models.receipt'),
        ),
    ]
