# Generated by Django 5.1 on 2025-01-09 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database_models', '0018_company_owner_alter_card_owner_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='owner',
        ),
    ]
