# Generated by Django 5.1 on 2025-01-09 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database_models', '0019_remove_company_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='increasebalancerequest',
            name='telegram_chat_id',
            field=models.CharField(blank=True, default='', max_length=20, null=True),
        ),
    ]
